### ISSUE TITLE
Non-merging IPSet

### ISSUE THREAD

**Issue by dcooper** [drkjam/netaddr#1]
Having an option on IPSet that does not merge adjacent networks would be very useful.

Eg.
>>> s = IPSet()
>>> s.add('192.168.0.0/24')
>>> s.add('192.168.1.0/24')
>>> s.iter_cidrs()
[IPNetwork('192.168.0.0/24'), IPNetwork('192.168.1.0/24')]

**Comment by juju4** [comment]
I think that's covered at least in part by spanning_cidr
https://github.com/drkjam/netaddr/issues/27

unless goal would be to merge with minimal/maximal number of non-include subnet. 
If I take back previous example
```
ip_list = []
ip_list.append(IPNetwork('201.103.181.0/24'))
ip_list.append(IPNetwork('201.103.182.0/24'))
ip_list.append(IPNetwork('201.103.183.0/24'))
ip_list.append(IPNetwork('201.103.184.0/24'))
ip_list.append(IPNetwork('201.103.185.0/24'))
ip_list.append(IPNetwork('201.103.186.0/24'))
ip_list.append(IPNetwork('201.103.187.0/24'))
ip_list.append(IPNetwork('201.103.188.0/24'))

```
I would look for a call like spanning_cidr(iplist, 2, 10) to say that I want to merge subnets with a minimum of 2 output prefix and a maximum of 10 to avoid including too much unknown IP for performance, security or whatever reasons.

result would be
```
spanning_cidr(ip_list, 0, 0)
# IPNetwork('201.103.176.0/20') ## no extra conditions, same than current spanning_cidr
spanning_cidr(ip_list, 0, 5)
# [IPNetwork('201.103.181.0/24'), IPNetwork('201.103.182.0/23'), IPNetwork('201.103.184.0/22'), IPNetwork('201.103.188.0/24')] ## same than cidr_merge
spanning_cidr(ip_list, 0, 2)
# IPNetwork('201.103.180.0/22'), IPNetwork('201.103.184.0/21') ## not sure if it's best result, but one
```
Not sure if there is an easy way to calculate size of non-overlapping space between ip_list and output. ideas?

Thanks

**Comment by drkjam** [comment]
Been open forever and not sure if it's that useful, so closing it.
