### ISSUE TITLE
nmap.py -  CIDR targets

### ISSUE THREAD

**Issue by auraltension** [drkjam/netaddr#100]
I'm keen to implement support for CIDR in `nmap.py`.  nmap supports CIDR so i think it'd be a good addition.

Before I get into it too much, I'm wondering you you've looked into this or had any thoughts around it?  I'm thinking at the moment that I could find the position of the cidr specification in `nmap_target_spec` and then utilise `netaddr.IPNetwork` to generate the IP addresses from it.

**Comment by RyPeck** [comment]
Hey @auraltension - I'm curious - is Nmap's targetting abilities not enough? Or are you referring to something other than the Nmap project?

http://nmap.org/book/man-target-specification.html

**Comment by auraltension** [comment]
Hi @RyPeck the nmap target spec is exactly what I want. According to that document:

`Nmap supports CIDR-style addressing. You can append /<numbits> to an IPv4 address or hostname and Nmap will scan every IP address for which the first <numbits> are the same as for the reference IP or hostname given`

However, this is how nmap.py currently acts:
```
>>> ips = nmap.iter_nmap_range('10.0.0.1-10')
>>> for i in ips:
...     print i
... 
10.0.0.1
10.0.0.2
10.0.0.3
10.0.0.4
10.0.0.5
10.0.0.6
10.0.0.7
10.0.0.8
10.0.0.9
10.0.0.10
>>> ips = nmap.iter_nmap_range('10.0.0.1/30')
>>> for i in ips:
...     print i
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nmap.py", line 92, in iter_nmap_range
    octet_ranges = _generate_nmap_octet_ranges(nmap_target_spec)
  File "nmap.py", line 65, in _generate_nmap_octet_ranges
    _nmap_octet_target_values(tokens[3]))
  File "nmap.py", line 40, in _nmap_octet_target_values
    octet = int(element)
ValueError: invalid literal for int() with base 10: '1/30'
```

The entire structure of nmap.py is set up to split on `.` and then find ranges within the octet, if you throw a `/<bits>` in there is borks.

I've messed with some ideas to implement this but haven't touched it since submitting this issue.
