### ISSUE TITLE
0.7.15 tarball is missing tests

### ISSUE THREAD

**Issue by jeckersb** [drkjam/netaddr#102]
For Fedora, we run the tests at package build time to sanity check that things work ok.  With the switch over to py.test in 0.7.15, it looks like the test/ directory doesn't make it into the tarball, which is what we're building from.

For 0.7.15, I'll grab the tests out of git and supply it as an additional source, but it would be great if the tests were included in the tarball for future releases.

**Comment by drkjam** [comment]
No worries. I had a choice to do it one way or the other. If this is easier for package maintainers, I'll certainly re-add tests to the archives for the next release.

**Comment by jeckersb** [comment]
Awesome, thanks!

**Comment by jlec** [comment]
thanks, also from the Gentoo side.
