### ISSUE TITLE
Support dialects for EUI-64 addresses

### ISSUE THREAD

**Issue by stymo** [drkjam/netaddr#105]
Is there a reason flexible formatting is only support ed for EUI-48 addresses? My app has a need, for example, to be able to normalize EUI-64 addresses to all alphanumeric characters as the mac_bare dialect class does for EUI-48 addresses. Is this planned for the future? Or are there reasons related to standards that type of formatting doesn't seem necessary?

**Comment by braaen** [comment]
Can you provide some example formats of what you have coming in and out?

**Comment by stymo** [comment]
I looked at #106 and I think this would handle what I need. 

One common use case for me is to go from what would be called a unix expanded dialect to a bare dialect, so input would be: "D8:1C:14:00:00:00:00:80" and output would be "D81C140000000080".

**Comment by drkjam** [comment]
Merged #106 which resolves this. Thanks @braaen and @stymo.
