### ISSUE TITLE
Identify registry of global IPv6 unicast allocations

### ISSUE THREAD

**Issue by aabdnn** [drkjam/netaddr#109]
I was writing some code to fetch the IPv4 and IPv6 address allocation files from IANA, when I discovered that netaddr already fetches the ipv4-address-space.xml file from IANA, and provides me with information about the designated registry for each /8 allocation in IPv4 address space. However, it provides no such information about IPv6 address space.

Is there any chance you could get it to also fetch ipv6-unicast-address-assignments.xml and provide similar information for IPv6 addresses?

**Comment by drkjam** [comment]
Yes, good idea, thanks for the ticket.

**Comment by aabdnn** [comment]
Thank you David! I appreciate this very much!

I noticed that you have removed the update function from iana.py. I know that global address allocations don't change much, but it was a useful function to have. In fact, I used it not too long ago to update my installation of netaddr with the latest file from iana. Why did you remove it?

**Comment by drkjam** [comment]
The code that updates these files is part of the build process (see `make download`). I deleted it from `iana.py` because I don't want to maintain this functionality in multiple places.

Let me know if you want to continue using the `iana.py` script and I will modify the Makefile to use that instead of `wget`.

**Comment by drkjam** [comment]
P.S. I'm doing a release in the next 24 hours so let me know ASAP - thanks!

**Comment by aabdnn** [comment]
I understand your reasoning to keep the logic in the Makefile. I just thought it was handy to have the update feature in iana.py, so one could update the files in case the IANA allocations change, and there isn't a new version of netaddr available yet. On the other hand this is such a rare event, that one could just download the file from IANA's website by hand.

I don't mind so much either way, so I will leave the decision to you. It's your code, and you know what's the best way to keep it organised :)

May I say how awesome netaddr is? It allows me to do so many useful things!
