### ISSUE TITLE
Observation: netaddr slower under pypy

### ISSUE THREAD

**Issue by aabdnn** [drkjam/netaddr#112]
Hi David. I apologise in advance if this is the wrong way to ask a question, but I couldn't find a mailing list of netaddr users. I have just observed something curious. One part of my code uses the cidr_merge() function of netaddr. Under cPython on my MacOSX laptop, a given merge takes about 3 seconds. The exact same program with the same inputs, running under pypy, takes 18 seconds for the merge.

Normally, just about any code given to pypy runs faster than under cPython. However, it seems that netaddr, or at least some parts of it, such as the cidr_merge, are running much more slowly. Is this a known issue?

**Comment by drkjam** [comment]
The mailing list we used in the past went away when Google closed them down. This Issues list is probably the best place for discussions in the absence of something better.

I'm not really sure why pypy is slower on the `cidr_merge()` operation. I don't routinely run netaddr on pypy. I do observe that the whole test suite is markedly slower on pypy than it used to be a few years ago. I don't know if this is down to changes in netaddr or pypy, or both. Perhaps we should introduce some performance testing in future to keep an eye on this.

If you or anyone else fancies benchmarking the code and reporting back here on specific operations or sections of code that are particularly slow we'd be happy to review. Pull requests with improvements are also very welcome ;)

**Comment by snordhausen** [comment]
Hi!

Which version of netaddr are you using? Up to 0.7.10, the code looked like this:
https://github.com/drkjam/netaddr/blob/a6727cc8c4a8fdb6f8b64c8e41d1d26ec6b7eefb/netaddr/ip/__init__.py#L1558

For version 0.7.11, the function was completely rewritten by Martijn van Oosterhout
https://github.com/drkjam/netaddr/blob/rel-0.7.x/netaddr/ip/__init__.py#L1529
If I remember correctly, this code was a few times faster than what we previously had.


> a given merge takes about 3 seconds

If that really applies to a single(!) run of cidr_merge, then you must have a LOT of IPs. The current implementation can merge 100,000 IPs in this benchmark...

```Python
import timeit
print timeit.repeat('cidr_merge(lots_of_ips)',
    setup='''
from netaddr import IPAddress, cidr_merge
lots_of_ips = [IPAddress(x) for x in xrange(100000)]''', number=1)
```
...in 1.52 seconds on my laptop.

**Comment by aabdnn** [comment]
Hi Stefan. I'm using netaddr 0.7.17 (and previously .15 and .14). Under all these versions, cidr_merge is very fast for me on cPython, but under pypy, it's very slow.
My specific use case is to read in all IP address allocations of each of the 5 regional Internet registries, and then making an IPSet of them of them. My program therefore reads in pretty much the entire allocated IP address space on the Internet, and this is much more than 100,000 :)

I haven't looked at the 2 different implementations of cidr_merge yet. When I get home, I will try to run my code under different versions of netaddr, as well as under cPython and pypy, and report what I find.

**Comment by aabdnn** [comment]
I have some simple observations now. With netaddr 0.7.17:

$ time python cidr-merge-test

real	0m6.763s
user	0m6.704s
sys	0m0.046s
$ time pypy cidr-merge-test

real	0m19.113s
user	0m18.985s
sys	0m0.079s

So pypy is much slower here than cPython. However, when I installed netaddr 0.7.10, I saw:

$ time python cidr-merge-test

real	0m27.069s
user	0m26.982s
sys	0m0.061s
$ time pypy cidr-merge-test

real	0m13.855s
user	0m13.747s
sys	0m0.073s


So cidr_merge() in netaddr 0.7.10 is slower than in 0.7.17. However, it runs about twice as fast under pypy. In 0.7.17, it is MUCH faster, but only under cPython. In pypy it is now much slower.

I know very little about pypy internal, but it's obviously not able to do it's "magic" for this function.

**Comment by snordhausen** [comment]
Hi!

After some intense staring at the algorithm, I noticed that it actually has a complexity of O(n^2). Testing with my little benchmark proved this:
* merging 100k takes 1.5 seconds
* merging 200k takes 6.0 seconds (not 3.0 seconds, as you would expect from O(n) algorithms)

With commit 9f2c51a1a6231b3c8ce82f18e06ed563ab13ee9b the algorithm now has a complexity of O(n) (or something very close to it):
* merging 100k takes 0.24 seconds
* merging 200k takes 0.48 (just as expected, and 12x as fast as before)

Go ahead and give it a try.

I don't think this will help Pypy, but maybe the 12x performance improvement makes up for that ;-)

**Comment by aabdnn** [comment]
OMG. You've worked a miracle here!! Previously, a given cidr merge took 6.8s on python, and 19s on pypy. With your patch, it now takes 4.6s on python, and 1.3s on pypy !!

I have also read that popping off the beginning of a list in python is very inefficient. Using the timeit module and comparing list.pop() versus list.pop(0) clearly shows the difference.

**Comment by drkjam** [comment]
Very nice!
