### ISSUE TITLE
netaddr.valid_mac('00-B0-D0-86-BB-F7')==False for 0.7.16 but True for 0.7.15

### ISSUE THREAD

**Issue by steveb** [drkjam/netaddr#114]
Assuming this is a valid MAC, this is a regression which is currently causing gate failures in unit test jobs on OpenStack.

The downstream bug is https://bugs.launchpad.net/heat/+bug/1490374

**Comment by kevinbenton** [comment]
looks like issue is that valid_mac is shadowed with another validation function.
https://github.com/drkjam/netaddr/blob/b2b83f5d69f7b38f31330624ec9eb292b1cc880d/netaddr/__init__.py#L42-L46

**Comment by lynic** [comment]
This issue affects both heat and neutron projects in openstack, cause unit test failure.
https://bugs.launchpad.net/neutron/+bug/1490380
