### ISSUE TITLE
all tests failing with python3 >= 3.5

### ISSUE THREAD

**Issue by anthraxx** [drkjam/netaddr#117]
- all pytests are failing with python3 >= 3.5
- they work fine for python2 >= 2.7.10

Solution:
- upgrade your internal pytest in runtests.py from 2.4.2 to something newer
- if i use my system pytest 2.8.2 everything is fine, its a pytest python3.5 issue that got fixed in a later release
- PS: Why are you even including your own outdated pytest 2.4.2 inside of runtests.py ? In my honest opinion that should get removed! Its a dependency and not something you should ship as base64 inside of runtests.py

Environment:

    ============================= test session starts ==============================
    platform linux -- Python 3.5.0 -- pytest-2.4.2
    collected 1 items / 23 errors
  
Summary of all 23 errors:

    E   TypeError: Call constructor takes either 0 or 3 positional arguments

Detailed trace of one example:

    _____________________ ERROR collecting core/test_compat.py _____________________
    _pytest.runner:137: in __init__
        ???
    _pytest.main:424: in _memocollect
        ???
    _pytest.main:303: in _memoizedcall
        ???
    _pytest.main:424: in <lambda>
        ???
    _pytest.python:370: in collect
        ???
    _pytest.python:1614: in parsefactories
        ???
    _pytest.python:229: in fget
        ???
    _pytest.python:367: in _getobj
        ???
    _pytest.main:303: in _memoizedcall
        ???
    _pytest.python:376: in _importtestmodule
        ???
    py._path.local:650: in pyimport
        ???
    <frozen importlib._bootstrap>:969: in _find_and_load
        ???
    <frozen importlib._bootstrap>:954: in _find_and_load_unlocked
        ???
    <frozen importlib._bootstrap>:892: in _find_spec
        ???
    <frozen importlib._bootstrap>:873: in _find_spec_legacy
        ???
    _pytest.assertion.rewrite:132: in find_module
        ???
    _pytest.assertion.rewrite:246: in _rewrite_test
        ???
    _pytest.assertion.rewrite:299: in rewrite_asserts
        ???
    _pytest.assertion.rewrite:413: in run
        ???
    /usr/lib/python3.5/ast.py:245: in visit
        return visitor(node)
    _pytest.assertion.rewrite:491: in visit_Assert
        ???
    /usr/lib/python3.5/ast.py:245: in visit
        return visitor(node)
    _pytest.assertion.rewrite:616: in visit_Compare
        ???
    /usr/lib/python3.5/ast.py:245: in visit
        return visitor(node)
    _pytest.assertion.rewrite:577: in visit_Call
        ???
    /usr/lib/python3.5/ast.py:245: in visit
        return visitor(node)
    _pytest.assertion.rewrite:521: in visit_Name
        ???
    E   TypeError: Call constructor takes either 0 or 3 positional arguments

**Comment by drkjam** [comment]
removed bundled pytest dependencies. Works for me under Python 3.5.x
