### ISSUE TITLE
Incorrect equality of IPNetwork host addresses

### ISSUE THREAD

**Issue by jimfunk** [drkjam/netaddr#118]
According to the documentation, IPNetwork is the class to use for a host address containing the prefix length. However, it seems that equality on these objects is not correct:

>>> IPNetwork('10.1.2.3/24') == IPNetwork('10.1.2.4/24')
True

**Comment by drkjam** [comment]
There is nothing wrong with the behaviour you are seeing. Please refer to the documentation for details https://pythonhosted.org/netaddr/tutorial_01.html#comparing-ip-addresses
