### ISSUE TITLE
Feature proposal: is_source() and  is_destination() methods for BaseIP class

### ISSUE THREAD

**Issue by pspacek** [drkjam/netaddr#119]
Hello,

current `BaseIP` class has method `is_reserved()` but this method does not convey full usage bits for reserved ranges as listed on http://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml (and respective page for IPv6).

Specifically, if an application wants to check 'Should I accept this IP address as source/destination address?' it will not have sufficient information, because some ranges can be reserved but still useabe (e.g. benchmarking ranges etc.).

I'm proposing to add methods `is_source(accept_special=False)` and `is_destination(accept_special=False)` to BaseIP class. These functions should match IP address with respective lines in table http://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml and return appropriate boolean from Source or Destination column.

Parameter `accept_special` (defaults to `False`) can be used to tell that ranges with note `Not useable unless by virtue of a more specific reservation.` should be accepted, too.

Would you accept PR implementing this idea?

Would it make sense to auto-generate dicts with respective values from XML files?

**Comment by drkjam** [comment]
Hi Petr,

Yes, your proposal sounds fine. Please do submit this as a pull request.

I definitely would generate the required code from the XML source files. Please follow conventions in the codebase for automatically downloading and keeping copies of the IANA files e.g. http://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xml (among others) which we make use of already.

Thanks.

**Comment by drkjam** [comment]
Outstanding for almost a year with no action. Long running tickets clutter up the issue tracker so closing this for now.
