### ISSUE TITLE
IPv4 and IPv6 Set comparison

### ISSUE THREAD

**Issue by Nuttycomputer** [drkjam/netaddr#120]
When comparing an ipv4 address to an ipv6 set or an ipv6 address to an ipv4 set it does not correctly report as true:

Example:
```
>>> ip_set = netaddr.IPSet(['::192.0.2.2/128'])

>>> ipv6 = netaddr.IPAddress('::192.0.2.2')
>>> ipv6 in ip_set
True

>>> ipv4 = netaddr.IPAddress('192.0.2.2')
>>> ipv4 in ip_set
False
```

You can work around this by converting an ipv4 object to ipv6 first adding the ipv4 compatible as appropriate

```
>>> ipv4_v6 = ipv4.ipv6(ipv4_compatible=True)
>>> ipv4_v6 in ip_set
True
```

I'm uncertain if this is desired behavior

**Comment by drkjam** [comment]
The behaviour you see is as expected. IPv4 address (without conversion) are not deemed equivalent to IPv6 addresses.
