### ISSUE TITLE
IPAddress() accepts string representations of integers to create IPv4 addreses, but not IPv6

### ISSUE THREAD

**Issue by dswhite42** [drkjam/netaddr#131]
```
>>> IPAddress(123456890, version=4)    # from int works
IPAddress('7.91.205.122')
>>> IPAddress('123456890', version=4)  # from str works
IPAddress('7.91.205.122')

>>> IPAddress(123456890, version=6)    # from int works
IPAddress('::7.91.205.122')
>>> IPAddress('123456890', version=6)  # from str FAILS
netaddr.core.AddrFormatError: base address '123456890' is not IPv6
```

**Comment by alexwlchan** [comment]
I had a quick look at this: it seems like the string-to-IP address conversion goes via `str_to_int()` in `netaddr.strategy.ipv6`, which in turn calls `socket.inet_pton()`. That’s what seems to be choking on these string addresses:

```pycon
>>> socket.inet_pton(socket.AF_INET6, '123456789')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: illegal IP address string passed to inet_pton
```

So perhaps detect whether the string can be coerced to an integer before passing to `inet_pton()`?

**Comment by drkjam** [comment]
Thinking about this, the constructor already has more than enough options for the majority of use cases. If you really have string representations of integers, I advise doing the type coercion from string to integer **before** you pass the value into netaddr's constructors.

**Comment by dswhite42** [comment]
Well, certainly you're at liberty to make it "won't fix", but it seems odd that out of 4 possible combinations (ipv4 from int, ipv4 from str, ipv6 from int, ipv4 from str), IPAddress() supports 3 of them but not the 4th.  Since auto-string conversion already happens for IPv4, wouldn't it just make it feature-complete to do the same thing for IPv6?   Again, it's minor... but perhaps just inconsistent for the method.
