### ISSUE TITLE
generate ip address list

### ISSUE THREAD

**Issue by wuwentao** [drkjam/netaddr#132]
Hi,

IPRange just support start/end address,as I just have one ip address ,and need to generate many different numbers IP/host list ,for example:

```
start_ip=1.1.1.1/32
numbers=50000
```

1. generate ip address list:
`ip_list=ip_range(start_ip,numbers)      `

2. ip address format:

```
end_ip=start_ip+numbers
for i in range(50000):
    start_ip=start_ip+1  （ format start_ip,and support  + or - steps/numbers ）

```
Thanks!

**Comment by drkjam** [comment]
Already supported (I believe).

You probably want something like this.

```
In [2]: from netaddr import *

In [3]: start_ip = IPAddress('1.1.1.1')

In [4]: for i in range(5):
   ...:     print start_ip + i
   ...:
1.1.1.1
1.1.1.2
1.1.1.3
1.1.1.4
1.1.1.5
```

**Comment by wuwentao** [comment]
seems I didn't found it in our help document,I will try to do it as your example.
Thanks very much!
