### ISSUE TITLE
Splitting a single network into multiple prefixed networks

### ISSUE THREAD

**Issue by alanwill** [drkjam/netaddr#133]
Is there a way to split a larger network into subnets of varying prefixes?

I saw that I can do the following:

```
ip = IPNetwork('172.24.0.0/16')
subnets = list(ip.subnet(23))
```

But I want to take that larger network and instead of just splitting it up equally into /23s I want to specify X number of /23 and Y number of /24s. I see there's a `count` available but no way to specify more than one prefix. 

Any way that netaddr can work for my use case? 

Thanks in advance

**Comment by RyPeck** [comment]
@alanwill you could first split it into a number of `/23` and then split a certain number of those into the number of `/24` you want. Quick example code off the top of my head - 

```
>>> from netaddr import *
>>> ip = IPNetwork('172.24.0.0/16')
>>> subnet_23 = list(ip.subnet(23))
>>> subnet_23[:6]
[IPNetwork('172.24.0.0/23'), IPNetwork('172.24.2.0/23'), IPNetwork('172.24.4.0/23'), IPNetwork('172.24.6.0/23'), IPNetwork('172.24.8.0/23'), IPNetwork('172.24.10.0/23')]
>>> len(subnet_23)
128
>>> final_subnets = []
>>> number_of_24s_wanted = 10
>>> for s in subnet_23:
...   if len(final_subnets) < number_of_24s_wanted:
...     final_subnets.extend(list(s.subnet(24)))
...   else:
...     final_subnets.append(s)
... 
>>> final_subnets[:20]
[IPNetwork('172.24.0.0/24'), IPNetwork('172.24.1.0/24'), IPNetwork('172.24.2.0/24'), IPNetwork('172.24.3.0/24'), IPNetwork('172.24.4.0/24'), IPNetwork('172.24.5.0/24'), IPNetwork('172.24.6.0/24'), IPNetwork('172.24.7.0/24'), IPNetwork('172.24.8.0/24'), IPNetwork('172.24.9.0/24'), IPNetwork('172.24.10.0/23'), IPNetwork('172.24.12.0/23'), IPNetwork('172.24.14.0/23'), IPNetwork('172.24.16.0/23'), IPNetwork('172.24.18.0/23'), IPNetwork('172.24.20.0/23'), IPNetwork('172.24.22.0/23'), IPNetwork('172.24.24.0/23'), IPNetwork('172.24.26.0/23'), IPNetwork('172.24.28.0/23')]
>>> len(final_subnets)
133
```

I suppose a function could be created for that operation.

**Comment by RyPeck** [comment]
Note - @alanwill also posted a StackOverflow question - http://stackoverflow.com/q/38864268/2158473.

**Comment by TomCos** [comment]
This module has a ton of potential.  I have some sample code to use IPSet to slice out of a supernet what's already in use (assuming you have this data from DNS, IPAM, etc...), then feed it back to the SubnetSplitter.  One change is, the SubnetSplitter will need to accept a set.  Can we find a way to expand the input?
Great job on this!
