### ISSUE TITLE
API reference is broken on ReadTheDocs

### ISSUE THREAD

**Issue by vfaronov** [drkjam/netaddr#137]
On http://pythonhosted.org/netaddr/api.html, I see a full API reference for netaddr, mostly class autodocs.

But on https://netaddr.readthedocs.io/en/latest/api.html, the sections only contain introductory text, no autodocs.

NB: ReadTheDocs supports building a “stable” version of docs and showing it by default. This can help avoid breaking docs with updates to master.

**Comment by sc68cal** [comment]
I just got bit by this trying to find the dialects that netaddr supports for mac addresses

**Comment by drkjam** [comment]
Done
