### ISSUE TITLE
declaring IPNetworks using a netmask

### ISSUE THREAD

**Issue by hunor-szombatfalvi** [drkjam/netaddr#139]
It's not really an issue, more like a feature request, so sorry if I'm asking in the wrong place but is there a way to declare something like "10.76.32.0 255.255.255.0" as an IPNetwork?

The format is not that important, I mean, what I'm asking is not if that exact format is supported but if it's possible to somehow use a netmask instead of a CIDR to declare an IPNetwork or IPSet.

Also, would there be a way to print IPSets without "IPSet([])" being specified in the output?
The same way you can do IPNetwork().ip or IPNetwork().netmask

**Comment by drkjam** [comment]
You can use a subnet mask in the IPNetwork constructor.

```
>>> IPNetwork("10.76.32.0/255.255.255.0")
IPNetwork('10.76.32.0/24')
```

IPSet doesn't support a __str__ method that is distinct from the __repr__ constructor view. Can't remember why I chose not to implement something more user friendly at the time.

The code to generate what you are looking for would be something like this.

```
>>> s = IPSet([IPNetwork("10.76.32.0/255.255.255.0")])

>>> ' '.join([str(x) for x in s.iter_cidrs()])
'10.76.32.0/24'
```
