### ISSUE TITLE
Convert list of IP CIDR strings to a human-readable glob

### ISSUE THREAD

**Issue by paragbaxi** [drkjam/netaddr#14]
From following site: http://stackoverflow.com/questions/6915999/python-convert-list-of-ip-cidr-strings-to-a-human-readable-glob

In netaddr module there are functions that convert either an ip range (iprange_to_globs(start, end)), or a CIDR (cidr_to_glob(cidr)) to a glob. A glob is a "user friendly form of specifying IP address ranges".

    >>> import netaddr
    >>> ip1 = netaddr.IPNetwork('10.0.0.0/23')
    >>> netaddr.cidr_to_glob(ip1)
    '10.0.0-1.*'

How to convert and merge multiple ip address ranges or CIDRs into the least amount of globs as possible? 
Example 1:

    >>> list_of_ips = ['10.0.0.0/23', '10.0.2.0/24', '10.0.3.0/24']
    >>> print glob_list(list_of_ips)
    '10.0.0-3.*'
Example 2:

    >>> list_of_ips2 = ['10.0.0.0/23', '10.0.3.0/24', '10.0.4.0/24']
    >>> print glob_list(list_of_ips2)
    '10.0.0-1.*, 10.0.3-4.*'

**Comment by drkjam** [comment]
This isn't going anywhere. Closing it. Please submit a pull request for consideration if progress is still desired.
