### ISSUE TITLE
Netaddr import error

### ISSUE THREAD

**Issue by wsummert-mobile** [drkjam/netaddr#141]
Command: from netaddr import *
Error - Import error: No moduled named contrib.subnet_splitter

I've installed netaddr from this Github repo but get this error when trying to import it in Python

![capture](https://cloud.githubusercontent.com/assets/23320692/20071775/a0c26d7c-a4da-11e6-866f-d879da6509a3.PNG)

**Comment by drkjam** [comment]
This is now fixed.
