### ISSUE TITLE
IPNetwork.subnet is calling self.__class__ with wrong arguments 

### ISSUE THREAD

**Issue by israel-lugo** [drkjam/netaddr#150]
Hello,

I created pull request #148 a few days ago, because ``IPNetwork.subnet()`` is actually working by luck, and doing more work than is necessary.

When doing the expansin, ``subnet`` is calling ``self.__class__`` like so:
```python
     subnet = self.__class__('%s/%d' % (base_subnet, prefixlen),
         self._module.version)
```

However,  class ``IPNetwork`` has the following signature:
```python
 def __init__(self, addr, implicit_prefix=False, version=None, flags=0):
```

The call above is missing an argument. This means the ``'%s/%d' % (base_subnet, prefixlen)`` goes correctly into ``addr``, but ``self._module.version`` goes into ``implicit_prefix``. That is not what you meant. This causes ``version`` to be None even though we already knew the IP version, meaning ``IPNetwork.__init__`` has to guess at the version. Also it causes ``implicit_prefix`` to always resolve True, meaning ``parse_ip_network`` will call ``cidr_abbrev_to_verbose`` when it didn't have to, since the prefix is already verbose.

All of this accumulates when we're subdividing a large number of networks. In my program [NetCalc](https://github.com/israel-lugo/netcalc), I have a hierarchical split mode in which I will split e.g. a /16 into its /17 halves, then each /17 its /18 halves, and so on. Testing with a split from a /14 to a /32, I spend 12% time inside ``IPNework.cidr_abbr_verbose`` (which is totally unnecessary in this case).

Can you please look over the pull request and merge?

Thank you,
Israel

**Comment by drkjam** [comment]
PR for this has been merged.
