### ISSUE TITLE
Glob produced from iprange_to_globs() not condensed

### ISSUE THREAD

**Issue by paragbaxi** [drkjam/netaddr#16]
Actual output:

    >>> iprange_to_globs('10.0.0.255', '10.0.255.255')
    ['10.0.0.255', '10.0.1.*', '10.0.2-3.*', '10.0.4-7.*', '10.0.8-15.*', '10.0.16-31.*', '10.0.32-63.*', '10.0.64-127.*', '10.0.128-255.*']

Expected output:

    >>> iprange_to_globs('10.0.0.255', '10.0.255.255')
    ['10.0.0.255', '10.0.1-255.*']

**Comment by drkjam** [comment]
This isn't going anywhere. Closing it.
