### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by plavine8183** [drkjam/netaddr#174]
root@won-la1-net01 scripts]# pip3 freeze
netaddr==0.7.19

[root@won-la1-net01 scripts]# /bin/sh /tmp/geany_run_script_COXYIZ.sh
Traceback (most recent call last):
  File "supernets.py", line 3, in <module>
    import netaddr
ModuleNotFoundError: No module named 'netaddr'

**Comment by tyler-8** [comment]
What are the contents of the shell script? Are you using virtual environments? You've not supplied anything that would indicate an issue with netaddr itself.

**Comment by snordhausen** [comment]
Not enough info to fix this (or find out if anything needs fixing).
