### ISSUE TITLE
valid_ipv4 returning 'True' for invalid IP addresses.

### ISSUE THREAD

**Issue by bradley-evans** [drkjam/netaddr#178]
I am using this library to try and identify if an entry in a log file constitutes a valid IPv4 address. Running the code in Python3, I get the following result:

```
Python 3.6.5 (default, Jun 17 2018, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from netaddr import valid_ipv4, valid_ipv6
>>> valid_ipv4('hi')
False
>>> valid_ipv4('79236720298')
True
>>>
```

I'm not sure that `'79236720298'` is supposed to constitute a valid IPv4 address.

**Comment by waynejohny** [comment]
This should be a valid ipv4 dec format

**Comment by drkjam** [comment]
You'll find that it isn't invalid (even though it does appear rather odd at first).

    In [1]: import socket

    In [2]: socket.inet_aton('79236720298')
    Out[2]: b'r\xe0f\xaa'

    In [3]: socket.inet_ntoa(socket.inet_aton('79236720298'))
    Out[3]: '114.224.102.170'
