### ISSUE TITLE
IPSet lacks indexing

### ISSUE THREAD

**Issue by qha** [drkjam/netaddr#18]
This makes it somewhat cumbersome to replace ip_set.random_ip() in ipaddr.py.

I've written a __getitem__ method for IPSet as a derived class. My intention is that it should be included in IPSet, but if a __getitem__ seems to odd for a form of set by all means leave it in a separate class.

[ edited in the hope of escaping markdown. ]

    #! /usr/bin/env python

    import netaddr
    import numbers

    class Ipset_indexable (netaddr.IPSet):
        def __getitem__(self, key):
            """Accessor.

            @param key: Index according to the sort_key ordering of
            IPNetworks/IPAddresses of the member to return.

            @return: The member at position C{key} in this IPSet.

    >>> ipset = Ipset_indexable()
    >>> ipset.add("192.168.0.0/24")
    >>> try:
    ...    ipset[27.5]
    ... except Exception, ee:
    ...     print ee.__class__.__name__, ee
    TypeError Ipset_indexable indices must be integers, not float
    >>> try:
    ...     ipset[2**8]
    ... except Exception, ee:
    ...     print ee.__class__.__name__, ee
    IndexError Ipset_indexable index out of range
    >>> ipset[-1]
    IPAddress('192.168.0.255')
    >>> ipset[2**5]
    IPAddress('192.168.0.32')
    >>> ipset.remove("192.168.0.32")
    >>> ipset[2**5]
    IPAddress('192.168.0.33')
    >>> ipset[-2**7]
    IPAddress('192.168.0.128')
    >>> try:
    ...     ipset[-2**8]
    ... except Exception, ee:
    ...     print ee.__class__.__name__, ee
    IndexError Ipset_indexable index out of range
    """
            if not isinstance(key, numbers.Integral):
                raise TypeError("%s indices must be integers, not %s"
                                % (self.__class__.__name__,
                                   key.__class__.__name__))

            if key >= 0:
                index = key
            else:
                index = len(self) + key

            if not (0 <= index < len(self)):
                raise IndexError("%s index out of range"
                                 % self.__class__.__name__)

            for net in sorted(self._cidrs):
                if index < len(net):
                    return net[index]
                index -= len(net)
                assert(index >= 0)

            # This should never happen:
            raise RuntimeError("%s indexing error"
                               % self.__class__.__name__)

    def _test():
        import doctest
        doctest.testmod()

    if __name__ == '__main__':
        _test()

**Comment by drkjam** [comment]
I don't really understand the requirement here. Sets are unordered containers and therefore don't (and shouldn't) support any form of indexing.
