### ISSUE TITLE
Special characters in strings causing DeprecationWarning output

### ISSUE THREAD

**Issue by stmcginnis** [drkjam/netaddr#184]
Using \ in strings now causes warnings with Python 3.6 and later for causing invalid escape sequences in regular strings.

"netaddr/strategy/eui48.py:123: DeprecationWarning: invalid escape sequence \."

https://github.com/drkjam/netaddr/blob/ebf714601e8cd6234575422f876d4d579b202b1a/netaddr/strategy/eui48.py#L123

These cases either need to be escaped or the string can be switched to a raw string (r"") to allow the use of special characters.

**Comment by syedsalmanalam1** [comment]
Change the line number 97 in  /usr/local/lib/python2.7/dist-packages/netaddr/__init__.py

data = fh.read(size).decode('UTF-8')
change it to 
data = fh.read(size).decode('UTF-8',errors='ignore')

**Comment by stmcginnis** [comment]
This is still an issue. Any chance we can get this merged soon?

**Comment by snordhausen** [comment]
Fixed with #185.
