### ISSUE TITLE
Ability to split IPNetwork into chunks using prefixlen

### ISSUE THREAD

**Issue by foxx** [drkjam/netaddr#61]
Hello,

I needed the ability to break up an IPNetwork (e.g. `172.16.1.0/24`) into even blocks of `/30`. This functionality is useful if you need automatically allocate the first available block of X.

I haven't finished writing all the unit tests and functionality, but here is a quick 5 minute knock up;

```python
import unittest
import netaddr
from netaddr import IPNetwork

######################## BEGIN NETADDR PATCHES ########################
split_list = lambda l, n: [l[x: x+n] for x in xrange(0, len(l), n)]

def split_network(network, prefixlen):
    """
    Break up a network into chunks using prefixlen
    Returns list of IPNetwork
    """

    if not isinstance(network, IPNetwork):
        raise ValueError, "network must be netaddr.IPNetwork()"

    if not isinstance(prefixlen, int) or prefixlen < 0 or prefixlen > 32:
        raise ValueError, "network must be int 0-32"

    cidr = "0/%s" % ( prefixlen, )
    ips_per_block = IPNetwork(cidr).size

    blocks = split_list(list(network), ips_per_block)
    valid_blocks = [ IPNetwork(block[0], prefixlen) for block in blocks if len(block) == ips_per_block ]
    invalid_blocks = [ block for block in blocks if len(block) != ips_per_block ]
    assert len(invalid_blocks) is 0
    return valid_blocks

class NetworkTest(unittest.TestCase):
    def test_split_network(self):
        valid_blocks = split_network(
            network=IPNetwork("192.168.0.0/24"), prefixlen=30)
        self.assertEquals(len(valid_blocks), 64)
```

Is this functionality something you would consider for the core? If so then I'll spent some time doing it properly and send a PR. Let me know, thanks!

PS) Great job on netattr, it's saved me tons of time

**Comment by drkjam** [comment]
netaddr already has this functionality covered via the IPNetwork.subnet method.

    >>> from netaddr import IPNetwork
    >>> list(IPNetwork("192.168.0.0/24").subnet(26))
    [IPNetwork('192.168.0.0/26'),
     IPNetwork('192.168.0.64/26'),
     IPNetwork('192.168.0.128/26'),
     IPNetwork('192.168.0.192/26')]
