### ISSUE TITLE
Bug in IP parsing

### ISSUE THREAD

**Issue by luisgf** [drkjam/netaddr#83]
Hello:

I'm trying to parse a list of IP coming from a ip-block-list. The problem arrive when i try to parse an address that is padded with 0. See an example:

Python 3.4.2 (default, Oct  8 2014, 13:08:17) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netaddr import IPAddress
>>> ip = IPAddress('218.077.079.043')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luisgf/python_virtualenvs/tfg/lib/python3.4/site-packages/netaddr/ip/__init__.py", line 307, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from '218.077.079.043'
>>>

**Comment by snordhausen** [comment]
Hi!

This can actually be made to work like this:

>>> ip = IPAddress('218.077.079.043', flags=netaddr.core.ZEROFILL)

which allows zero-padded IPs. I actually just found this feature while looking through the code.

Producing output in this zero-padded format is not possible out of the box. But issue #82 requests something similar, so I will close this ticket.
