### ISSUE TITLE
Incorrect python executable path in netaddr-0.7.13-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by Abhishek-Srivastava** [drkjam/netaddr#84]
Hi,

With the whl netaddr-0.7.13-py2.py3-none-any.whl, the bin file which is getting generated is with this executable : #!/Users/drkjam/pythonenv/netaddr/bin/python

Can you please fix this?

**Comment by snordhausen** [comment]
Hi!

I can reproduce this problem with these shell commands:

wget -O netaddr_wheel.zip  https://pypi.python.org/packages/any/n/netaddr/netaddr-0.7.13-py2.py3-none-any.whl
unzip netaddr_wheel.zip

Followed by

grep -R "/Users/drkjam" netaddr-0.7.13.data


Interestingly, the shebang is correct in our repository. I guess something went wrong during the build process, so I'll assign this one to drkjam

**Comment by snordhausen** [comment]
Did this work correctly in 0.7.12? I cannot find a WHL file for this version, so I cannot check myself.

**Comment by Abhishek-Srivastava** [comment]
Yes it works fine in 7.12. I too couldn't find a whl. for 7.12 but its available for 7.13.
A similar issue was found in jsonpointer which got fixed: https://github.com/stefankoegl/python-json-pointer/issues/15#issuecomment-67284066

**Comment by zwant** [comment]
+1 on this getting fixed! Prevents me from installing netaddr through wheel in a virtualenv

**Comment by KoleS46** [comment]
Just got it in 0.7.12 egg
    error: Failed dependencies:
        /Users/drkjam/pythonenv/netaddr/bin/python is needed by

**Comment by arhbkb** [comment]
I've also just run into this problem:

$ netaddr 
-bash: /Users/anandb/venv/mypy/bin/netaddr: /Users/drkjam/pythonenv/netaddr/bin/python: bad interpreter: No such file or directory

Can someone please fix the wheel ASAP?

**Comment by drkjam** [comment]
Pushed a fix for this issue. Can someone clone the repo and test that it is working for them?

**Comment by drkjam** [comment]
fixed and released in netaddr 0.7.14

**Comment by snordhausen** [comment]
For anyone having the same problem, the fix was commit  7b664e593a756bdd43d8c338bff56a5a8d49951d
