### ISSUE TITLE
IPSet missing method add(IPSet)

### ISSUE THREAD

**Issue by perw07** [drkjam/netaddr#85]
It is possible to add objects of type IPRange as well as networks as IPNetwork or strings, but it is not possible to add objects of type IPSet to an IPSet.

I think this is a lack of symmetry, I cannot use 'ipset.add(object)' for all netaddr objects.

Adding support for IPSet objects to the method add() probably has no drawbacks, and helps in some cases.

**Comment by snordhausen** [comment]
The current behavior is in line with Python's "set" objects:

>>> a = set([1,2,3])
>>> b = set([3,4,5])
>>> a.add(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'set'

However, you do have a point that it is annoying to use add() for almost everything, except for IPSets where you need to use update(). I think we should implement this.

**Comment by drkjam** [comment]
This ticket is long outstanding and isn't moving forward. Please submit a pull request for consideration via a new ticket if you wish to see this idea make progress.
