### ISSUE TITLE
problem parsing mac address to manufacturer

### ISSUE THREAD

**Issue by localtracker** [drkjam/netaddr#89]
Ok this is the problem I am facing. I have a mac address: 70:11:24:e6:68:96 . I am trying this:

>>> mac = EUI('70:11:24:e6:68:96')
>>> mac.oui.registration().org
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/netaddr/eui/__init__.py", line 414, in oui
    return OUI(self.value >> 24)
  File "/usr/lib/python2.7/dist-packages/netaddr/eui/__init__.py", line 110, in __init__
    raise NotRegisteredError('OUI %r not registered!' % oui)
netaddr.core.NotRegisteredError: OUI 7344420 not registered!

Now when I try this:

>>> mac = EUI('7344420')
>>> mac.oui.registration().org
'XEROX CORPORATION'

It resolves!! What is going wrong here?

**Comment by snordhausen** [comment]
Hi!

Which version are you using? Version 0.7.13 had issue #81 which might trigger this behavior. With version 0.7.14, your code works for me.

**Comment by localtracker** [comment]
yep I have an older version, but how do I get around this?

pip install netaddr --upgrade
Collecting netaddr
  Using cached netaddr-0.7.14-py2.py3-none-any.whl
Installing collected packages: netaddr
  Found existing installation: netaddr 0.7.7
    DEPRECATION: Uninstalling a distutils installed project (netaddr) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'netaddr'. No files were found to uninstall.
Successfully installed netaddr-0.7.7

**Comment by snordhausen** [comment]
Google found this solution for your "No files were found to uninstall" problem:

http://stackoverflow.com/questions/13136060/pip-cannot-uninstall-pysqlite
