### ISSUE TITLE
Investigate Superceding IPy

### ISSUE THREAD

**Issue by autocracy** [drkjam/netaddr#90]
The IPy library I maintain features the same goals as netaddr and the same basic features: IPv4, IPv6, and IPSet functionality.

This issue is to discuss ensuring full feature overlap of IPy features in netaddr's native interface and an IPy interface that passes all existing IPy API calls. This would provide the possibility that there can be a clear path and precedence of which library to use and allow shuttering of one project. Maintainers: please let me know if this proposal interests you. It does come with a commitment that I will heavily contribute to making it possible.

**Comment by drkjam** [comment]
Thanks for getting in touch. To clarify, are you talking about shuttering IPy and transitioning its existing users over to netaddr?

**Comment by autocracy** [comment]
Assuming it can be a full drop-in for IPy, yes. My goal would be to have the IPy library exported by netaddr as a deprecated interface and guide future OS packagers to mark netaddr packages as providing IPy and verifying that this doesn't actually occur: https://github.com/trigger/trigger/issues/61

**Comment by drkjam** [comment]
OK. Let's do the groundwork for this ticket on a feature branch to tease out any thorny issues and see how tricky it would be to get it working.

netaddr has a lower-level API below the class interfaces which should (fingers crossed) make implementing an IPy interface fairly straightforward. The one unknown quantity may be the IPSet functionality - hopefully there won't be too many differences between the two.

I suggest trying to see if we can reach full feature compatibility and then start looking at benchmarks to address any performance concerns.

**Comment by drkjam** [comment]
@autocracy I haven't had a huge amount of time to work on this. Have you had any time to make any progress yourself?

**Comment by autocracy** [comment]
Nor I. I should prioritize the first part of setting up the testing interface so I can work on it one method at a time.

**Comment by drkjam** [comment]
Outstanding for more than a year and I don't think this is going anywhere (I certainly don't have bandwidth to give it serious consideration). Closing it.
