### ISSUE TITLE
Ability to get natural netmask for an address

### ISSUE THREAD

**Issue by mjaustin2** [drkjam/netaddr#97]
When parsing routing tables from cisco equipment, routes to subnets that use their natural netmask are listed with no CIDR. For instance, 192.168.1.0/24 would be shown as just 192.168.1.0 since /24 is the natural netmask of a Class C address. It would be nice to have a method that given an address, would return the natural netmask. Something like:

netaddr.natural_netmask('192.168.1.2') would return the integer 24.
netaddr.natural_netmask('172.16.0.0') would return the integer 16.
netaddr.natural_netmask('10.1.2.3') would return the integer 8.

Bonus points if there's a param to have it return the network and CIDR.

netaddr.natural_netmask('192.168.1.2',return_net=true) would return the string 192.168.1.0/24.

Thanks!

**Comment by drkjam** [comment]
Like this?

>>> IPNetwork(cidr_abbrev_to_verbose('192.168.1.2')).cidr
IPNetwork('192.168.1.0/24')

**Comment by RyPeck** [comment]
@mjaustin2 - Would you expect this behavior only for the RFC1918 space?

**Comment by braaen** [comment]
Would you be able to parse things using the implicit_prefix that is currently an attribute of the IPNetwork.__init__() function?

i.e.
>>> IPNetwork('192.168.1.2', implicit_prefix=True)
IPNetwork('192.168.1.2/24')

**Comment by drkjam** [comment]
@mjaustin2 any further comments on this?

**Comment by drkjam** [comment]
No traction on this ticket. If there are no further comments or updates I'm going to close this without making any changes.

**Comment by drkjam** [comment]
@snordhausen are you happy to close this ticket?
